project1: ternary testing
	g++ -g ternary.o  testing.o -o project1.out

all: ternary testing
	g++ -g ternary.o  testing.o -o main 

ternary: ternary.cpp
	g++ -g -c ternary.cpp

testing: testing.cpp
	g++ -g -c testing.cpp
